In [1]:
# import pandas library for data manipulation and analysis
import pandas as pd

In [2]:
# reading the csv files into separate dataframes
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [3]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country', 'director', 'actors']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

In [4]:
# display the dataframe df_movies
df_movies

,imdb_title_id,title,year,genre,country,director,actors
0,tt0000009,Miss Jerry,1894,Romance,USA,Alexander Black,"Blanche Bayliss, William Courtenay, Chauncey D..."
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,Charles Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be..."
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",Urban Gad,"Asta Nielsen, Valdemar Psilander, Gunnar Helse..."
3,tt0002101,Cleopatra,1912,"Drama, History",USA,Charles L. Gaskill,"Helen Gardner, Pearl Sindelar, Miss Fielding, ..."
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,"Francesco Bertolini, Adolfo Padovan","Salvatore Papa, Arturo Pirovano, Giuseppe de L..."
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",Ludovic Colbeau-Justin,"Dany Boon, Philippe Katerine, Anne Serra, Samu..."
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,Johan Nijenhuis,"Herman Finkers, Johanna ter Steege, Leonie ter..."
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,Vineesh Aaradya,"Anoop Chandran, Indrans, Sona Nair, Simon Brit..."
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,Ahmet Faik Akinci,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,..."
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,Laura Jou,"Maria Morera Colomer, Biel Rossell Pelfort, Is..."

In [5]:
# display the dataframe df_ratings
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

## **concat()**

### **Concatenate Vertically**

To concatenate vertically (along hte rows) we should have columns in common between the 2 dataframes

In [6]:
# create first dataframe with id and age columns
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 23, 25, 22]})

# create second dataframe with id and age columns
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'H'],
                   'age': [40, 21, 19, 24]})

In [7]:
# concatenate df1 and df2 into a single dataframe (vertically)
pd.concat([df1, df2])

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
0  E   40
1  F   21
2  G   19
3  H   24

In [8]:
# extract a 50% sample of the original dataframe
df_sample = df_movies.sample(frac=0.5)

# show dataframe
df_sample

,imdb_title_id,title,year,genre,country,director,actors
66348,tt2328490,The Formula,2014,"Comedy, Romance",USA,"Thomas Beecher, Joe Clarke","Brandon Baker, Mike Schminke, Sasha Jackson, R..."
72063,tt3647498,Blood Father,2016,"Action, Crime, Drama",France,Jean-François Richet,"Mel Gibson, Erin Moriarty, Diego Luna, Michael..."
81362,tt6858002,Shishûgoku: Ki no hen,2017,Horror,Japan,Hideo Jôjô,"Moemi Katayama, Anna Tachibana, Shin'ichi Wagô..."
31269,tt0120722,Kiss,1998,"Comedy, Drama, Romance",USA,Richard LaGravenese,"Holly Hunter, Danny DeVito, Queen Latifah, Mar..."
41343,tt0306444,Aida degli alberi,2001,"Animation, Family, Musical","Italy, UK",Guido Manuli,"Vittorio Bestoso, Massimo Bitossi, Simone D'An..."
...,...,...,...,...,...,...,...
44863,tt0390649,Zhifu,2003,"Drama, Thriller","China, Hong Kong",Yi'nan Diao,"Kai Han, Hongli Liang, Hua Qin, Xueqiong Zeng"
51961,tt0975744,Tamnaan somdet phra Naresuan maharat: Phaak pr...,2007,"Action, Drama, History",Thailand,Chatrichalerm Yukol,"Wanchana Sawatdee, Nopachai Chaiyanam, Thaksaw..."
48789,tt0483706,Das kleine Arschloch und der alte Sack - Sterb...,2006,"Animation, Comedy",Germany,"Michael Schaack, Konrad Weise","Ilona Schulz, Helge Schneider, Henni Nachtshei..."
55074,tt11810546,Beyond the Dream,2019,"Mystery, Romance",Hong Kong,Kiwi Chow,"Chun-Him Lau, Cecilia Choi, Hee Ching Paw, Cha..."
25796,tt0101492,No Control - Fuori controllo,1991,"Horror, Sci-Fi, Thriller",USA,Eric Red,"Jeff Fahey, Lindsay Duncan, Kim Delaney, Zakes..."

In [9]:
# shape of the dataframe that we'll concatenate
print(df_movies.shape)
print(df_sample.shape)

(85855, 7)
(42928, 7)

In [10]:
# concatenate df_movies and df_sample (vertically along the rows)
df_concat_vertically = pd.concat([df_movies, df_sample])

# show dataframe
df_concat_vertically

,imdb_title_id,title,year,genre,country,director,actors
0,tt0000009,Miss Jerry,1894,Romance,USA,Alexander Black,"Blanche Bayliss, William Courtenay, Chauncey D..."
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,Charles Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be..."
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",Urban Gad,"Asta Nielsen, Valdemar Psilander, Gunnar Helse..."
3,tt0002101,Cleopatra,1912,"Drama, History",USA,Charles L. Gaskill,"Helen Gardner, Pearl Sindelar, Miss Fielding, ..."
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,"Francesco Bertolini, Adolfo Padovan","Salvatore Papa, Arturo Pirovano, Giuseppe de L..."
...,...,...,...,...,...,...,...
44863,tt0390649,Zhifu,2003,"Drama, Thriller","China, Hong Kong",Yi'nan Diao,"Kai Han, Hongli Liang, Hua Qin, Xueqiong Zeng"
51961,tt0975744,Tamnaan somdet phra Naresuan maharat: Phaak pr...,2007,"Action, Drama, History",Thailand,Chatrichalerm Yukol,"Wanchana Sawatdee, Nopachai Chaiyanam, Thaksaw..."
48789,tt0483706,Das kleine Arschloch und der alte Sack - Sterb...,2006,"Animation, Comedy",Germany,"Michael Schaack, Konrad Weise","Ilona Schulz, Helge Schneider, Henni Nachtshei..."
55074,tt11810546,Beyond the Dream,2019,"Mystery, Romance",Hong Kong,Kiwi Chow,"Chun-Him Lau, Cecilia Choi, Hee Ching Paw, Cha..."
25796,tt0101492,No Control - Fuori controllo,1991,"Horror, Sci-Fi, Thriller",USA,Eric Red,"Jeff Fahey, Lindsay Duncan, Kim Delaney, Zakes..."

In [11]:
# shape of the concatenated dataframe
df_concat_vertically.shape

(128783, 7)

### **Concatenate Horizontally**

To concatenate horizontally (along the columns) we should have a common index between the 2 dataframes

In [12]:
# create first dataframe with id and age columns
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 23, 25, 22]})

# create second dataframe with job column
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})

In [13]:
# concatenate df1 and df2 into a single dataframe (horizontally)
pd.concat([df1, df2], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

In [14]:
# sahpe of dataframe
print(df_movies.shape)
print(df_ratings.shape)

(85855, 7)
(85855, 3)

In [15]:
# set imdb_title_id as index for movies and ratings dataframe
df_movies = df_movies.set_index('imdb_title_id')
df_ratings = df_ratings.set_index('imdb_title_id')

In [16]:
# sahpe of dataframe that we'll concatenate
print(df_movies.shape)
print(df_ratings.shape)

(85855, 6)
(85855, 2)

In [17]:
# concatenate df_movies and df_ratings on imdb_title_id (horizontally along the columns)
df_concat_horizontally = pd.concat([df_movies, df_ratings], axis=1)

# show dataframe
df_concat_horizontally

,title,year,genre,country,director,actors,total_votes,mean_vote
imdb_title_id,,,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,Alexander Black,"Blanche Bayliss, William Courtenay, Chauncey D...",154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,Charles Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",Urban Gad,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,Charles L. Gaskill,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,"Francesco Bertolini, Adolfo Padovan","Salvatore Papa, Arturo Pirovano, Giuseppe de L...",2237,6.9
...,...,...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",Ludovic Colbeau-Justin,"Dany Boon, Philippe Katerine, Anne Serra, Samu...",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,Johan Nijenhuis,"Herman Finkers, Johanna ter Steege, Leonie ter...",724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,Vineesh Aaradya,"Anoop Chandran, Indrans, Sona Nair, Simon Brit...",265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,Ahmet Faik Akinci,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...",194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,Laura Jou,"Maria Morera Colomer, Biel Rossell Pelfort, Is...",102,6.8

In [18]:
# shape of the concatenated dataframe
df_concat_horizontally.shape

(85855, 8)