In [1]:
# import pandas library for data manipulation and analysis
import pandas as pd

In [2]:
# reading the csv file
df_cars = pd.read_csv('Car_sales.csv')

In [3]:
# selecting columns
df_cars = df_cars[['Manufacturer', 'Sales_in_thousands', 'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower', 'Fuel_capacity']]

In [4]:
# show dataframe
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [5]:
# calculate number of unique values
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

## **agg ()**

In [6]:
# calculate the sum of columns
df_cars.agg('sum', numeric_only=True)

Sales_in_thousands     8320.698
Price_in_thousands     4245.567
Engine_size             477.500
Horsepower            29008.000
Fuel_capacity          2800.500
dtype: float64

In [7]:
# calculate the mean of numeric columns
df_cars.agg('mean', numeric_only=True)

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [8]:
# calculate the mean and count values
df_cars.select_dtypes(include='number').agg(['mean', 'count'])

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,52.998076,27.390755,3.060897,185.948718,17.951923
count,157.000000,155.000000,156.000000,156.000000,156.000000

In [9]:
# different aggregation per column: calculate the sum and mean of 'Sales_in_thousands' & sum and max of 'Price_in thousands'
df_cars.agg({'Sales_in_thousands': ['sum', 'mean'], 'Price_in_thousands': ['sum', 'max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [10]:
# aggregate over the columns
df_cars[['Sales_in_thousands', 'Price_in_thousands']].agg('sum', axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [11]:
# equivalent (NaN behaves differently)
df_cars['Sales_in_thousands'] + df_cars['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [12]:
# aggregate different functions and rename the index of the resulting dataframe
df_cars.agg(x=('Sales_in_thousands', 'sum'), y=('Price_in_thousands', 'mean'))

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN           27.390755

## **The Split-Apply-Combine Strategy**

In [13]:
# split data into separate groups
car_filter = df_cars['Vehicle_type']=='Car'
passenger_filter = df_cars['Vehicle_type']=='Passenger'

In [14]:
# apply an operation
car_average = df_cars[car_filter]['Sales_in_thousands'].mean()
passenger_average = df_cars[passenger_filter]['Sales_in_thousands'].mean()

In [15]:
# combine results
pd.DataFrame({'Vehicle_type': ['Car', 'Passenger'], 'Sales_in_thousands': [car_average, passenger_average]}).set_index('Vehicle_type')

              Sales_in_thousands
Vehicle_type
Car                    80.622293
Passenger              43.234345

## **groupby()**

In [16]:
# group by vehicle type and calculate the mean
df_cars.groupby('Vehicle_type').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Car,80.622293,26.319975,3.520000,186.400000,21.895000
Passenger,43.234345,27.763200,2.902586,185.793103,16.592241

In [17]:
# group by manufacturer
groupby_obj = df_cars.groupby('Manufacturer')

In [18]:
# the groupby_obj
groupby_obj

In [19]:
# groups attibutes and keys
groupby_obj.groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [20]:
# get a specific group within the manufacturer column
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [21]:
# group by manufacturer and calculate the mean
df_cars.groupby('Manufacturer').mean(numeric_only=True).head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.751250,30.633333,2.925000,200.000000,16.400000
Audi,13.519000,39.980000,2.933333,220.000000,19.533333
BMW,15.501667,33.096667,2.700000,185.333333,17.233333
Buick,60.504750,26.781250,3.625000,206.250000,17.750000
Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000

In [22]:
# group by manufacturer and calculate the sum
df_cars.groupby('Manufacturer').sum(numeric_only=True).head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,79.005,91.900,11.7,800.0,65.6
Audi,40.557,119.940,8.8,660.0,58.6
BMW,46.505,99.290,8.1,556.0,51.7
Buick,242.019,107.125,14.5,825.0,71.0
Cadillac,112.178,201.270,22.5,1280.0,104.0

In [23]:
# group by vehicle_type and count the values
df_cars.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [24]:
# find the null values in the column
df_cars.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [25]:
# group by enngine_size and count values without dropping NaN values
df_cars.groupby('Engine_size', dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

## **groupby() & agg()**

In [26]:
# find the minimum and maximum values on each column
df_cars.groupby('Vehicle_type').agg(['min', 'max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [27]:
# set a name for aggregated column
# find the min engine_size and max horsepower
df_cars.groupby('Vehicle_type').agg(min_engine_size=('Engine_size', 'min'), max_horsepower=('Horsepower', 'max'))

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [28]:
# calculate the sum of 'Sales_in_thousands' and mean of 'Price_in_thousands'
df_cars.groupby('Manufacturer').agg(sum_sales=('Sales_in_thousands', 'sum'), mean_price=('Price_in_thousands', 'mean')).head()

              sum_sales  mean_price
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000

In [29]:
df_cars.groupby('Manufacturer').sum()['Sales_in_thousands'].head()

Manufacturer
Acura        79.005
Audi         40.557
BMW          46.505
Buick       242.019
Cadillac    112.178
Name: Sales_in_thousands, dtype: float64

In [30]:
df_cars.groupby('Manufacturer').mean(numeric_only=True)['Price_in_thousands'].head()

Manufacturer
Acura       30.633333
Audi        39.980000
BMW         33.096667
Buick       26.781250
Cadillac    40.254000
Name: Price_in_thousands, dtype: float64

## **Lambda**

Apply your own function

In [31]:
df_cars.groupby('Manufacturer').sum(numeric_only=True).head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,79.005,91.900,11.7,800.0,65.6
Audi,40.557,119.940,8.8,660.0,58.6
BMW,46.505,99.290,8.1,556.0,51.7
Buick,242.019,107.125,14.5,825.0,71.0
Cadillac,112.178,201.270,22.5,1280.0,104.0

In [32]:
# get actual sales and price values
df_cars.groupby('Manufacturer').sum()[['Sales_in_thousands', 'Price_in_thousands']].apply(lambda x: x*1000).head()

              Sales_in_thousands  Price_in_thousands
Manufacturer
Acura                    79005.0             91900.0
Audi                     40557.0            119940.0
BMW                      46505.0             99290.0
Buick                   242019.0            107125.0
Cadillac                112178.0            201270.0

In [33]:
# subtract values from the mean of each group
df_cars.groupby('Manufacturer').apply(lambda x: x.select_dtypes(include='number') - x.select_dtypes(include='number').mean())

/tmp/ipython-input-2732855851.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cars.groupby('Manufacturer').apply(lambda x: x.select_dtypes(include='number') - x.select_dtypes(include='number').mean())

                  Sales_in_thousands  Price_in_thousands  Engine_size  \
Manufacturer
Acura        0             -2.832250           -9.133333    -1.125000
             1             19.632750           -2.233333     0.275000
             2             -5.637250                 NaN     0.275000
             3            -11.163250           11.366667     0.575000
Audi         4              6.878000          -15.990000    -1.133333
...                              ...                 ...          ...
Volvo        152           -9.078333           -6.533333    -0.400000
             153            2.621667           -3.433333     0.100000
             154            4.907667           -2.133333     0.100000
             155           -9.130333           14.566667     0.000000
             156            6.345667            5.066667     0.600000

                  Horsepower  Fuel_capacity
Manufacturer
Acura        0    -60.000000      -3.200000
             1     25.000000       0.800000
             2     25.000000       0.800000
             3     10.000000       1.600000
Audi         4    -70.000000      -3.133333
...                      ...            ...
Volvo        152  -22.166667      -2.033333
             153  -14.166667       0.066667
             154  -14.166667       0.066667
             155   53.833333       0.666667
             156   18.833333       3.266667

[157 rows x 5 columns]

In [34]:
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [35]:
df_cars.groupby('Manufacturer').mean(numeric_only=True).head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.751250,30.633333,2.925000,200.000000,16.400000
Audi,13.519000,39.980000,2.933333,220.000000,19.533333
BMW,15.501667,33.096667,2.700000,185.333333,17.233333
Buick,60.504750,26.781250,3.625000,206.250000,17.750000
Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000

## **Filteration**

In [36]:
# calculate the maen of Sales_in_thousands
df_cars.mean(numeric_only=True)

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [37]:
# filter certain values out based on sum() and return a subset
def filter_func(x):
  return x['Sales_in_thousands'].sum() > 52

df_filter = df_cars.groupby(['Manufacturer']).filter(filter_func)
df_filter

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.500,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.400,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.000,3.5,210.0,18.0
10,Buick,91.561,Passenger,21.975,3.1,175.0,17.5
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.400,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.500,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.800,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.500,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.000,2.9,201.0,21.1

In [38]:
df_cars.groupby(['Manufacturer']).sum(numeric_only=True)['Sales_in_thousands'].sort_values().head(7)

Manufacturer
Porsche     12.128
Jaguar      15.467
Saab        21.306
Infiniti    23.713
Audi        40.557
BMW         46.505
Plymouth    64.001
Name: Sales_in_thousands, dtype: float64

In [39]:
df_cars[df_cars['Manufacturer'].isin(['BMW', 'Audi', 'Infiniti', 'Saab', 'Jaguar', 'Porsche'])].shape

(13, 7)

In [40]:
print(df_cars.shape)
print(df_filter.shape)

(157, 7)
(144, 7)