In [1]:
# import pandas library for data manipulation and analysis
import pandas as pd

In [2]:
# reading the csv files into separate dataframes
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [3]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

In [4]:
# display the dataframe df_movies
df_movies

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [5]:
# display the dataframe df_ratings
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

## **merge()**

In [6]:
# create first dataframe with id and age columns
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 23, 25, 22]})

# create second dataframe with id and job column
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})

In [7]:
# show dataframe df1
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [8]:
# show dataframe df1
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

## **Inner Join : (A ∩ B)**

In [9]:
# merge df1 and df2 on 'id' using inner join
df1_merge_inner_df2 = df1.merge(df2, how='inner', on='id')

In [10]:
# merged dataframe using inner join
df1_merge_inner_df2

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [11]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_inner_df2.shape)

(4, 2)
(4, 2)
(2, 3)

In [12]:
# merge df_movies and df_ratings (inner join)
df_inner_join = df_movies.merge(df_ratings, how='inner', on='imdb_title_id')

In [13]:
# show merged dataframe using inner join
df_inner_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [14]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_inner_join.shape)

(85855, 5)
(85855, 3)
(85855, 7)

## **Outer Join (Full Join) : (A ∪ B)**

In [15]:
# merge df1 and df2 on 'id' using outer join
df1_merge_outer_df2 = df1.merge(df2, how='outer', on='id')

In [16]:
# merged dataframe using outer join
df1_merge_outer_df2

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [17]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_outer_df2.shape)

(4, 2)
(4, 2)
(6, 3)

In [18]:
# merge df_movies and df_ratings (outer join)
df_outer_join = df_movies.merge(df_ratings, how='outer', on='imdb_title_id')

In [19]:
# show merged dataframe using outer join
df_outer_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [20]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_outer_join.shape)

(85855, 5)
(85855, 3)
(85855, 7)

## **Exclusive Outer Join (Exclusive Full Join) : (A ∪ B) – (A ∩ B)**

In [21]:
# outer join
df1_merge_outer_df2 = df1.merge(df2, how='outer', on='id')
df1_merge_outer_df2

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [22]:
# indicator=True
df1_merge_outer_df2 = df1.merge(df2, how='outer', on='id', indicator=True)
df1_merge_outer_df2

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [23]:
# query (for exclusive outer join)
df1_merge_exclusive_outer_df2 = df1_merge_outer_df2.query('_merge == "left_only" or _merge == "right_only"')
df1_merge_exclusive_outer_df2

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [24]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_exclusive_outer_df2.shape)

(4, 2)
(4, 2)
(4, 4)

In [25]:
# outer join
df_outer_join = df_movies.merge(df_ratings, how='outer', on='imdb_title_id')
df_outer_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [26]:
# indicator=True
df_outer_join = df_movies.merge(df_ratings, how='outer', on='imdb_title_id', indicator=True)
df_outer_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [27]:
# query (for exclusive outer join)
df_exclusive_outer_join = df_outer_join.query('_merge == "left_only" or _merge == "right_only"')
df_exclusive_outer_join

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [28]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_exclusive_outer_join.shape)

(85855, 5)
(85855, 3)
(0, 8)

## **Left Join : A + (A ∩ B)**

In [29]:
# merge df1 and df2 on 'id' using left join
df1_merge_left_df2 = df1.merge(df2, how='left', on='id')

In [30]:
# merged dataframe using left join
df1_merge_left_df2

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

In [31]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_left_df2.shape)

(4, 2)
(4, 2)
(4, 3)

In [32]:
# merge df_movies and df_ratings (left join)
df_left_join = df_movies.merge(df_ratings, how='left', on='imdb_title_id')

In [33]:
# show merged dataframe using left join
df_left_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [34]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_left_join.shape)

(85855, 5)
(85855, 3)
(85855, 7)

More example for better understanding (of Left Join)

In [35]:
# extract 50% sample of the df_movies dataframe
df_movies_sample = df_movies.sample(frac=0.5)

In [36]:
# merge df_movies_sample and df_ratings (left join)
df_left_join_example = df_movies_sample.merge(df_ratings, how='left', on='imdb_title_id')

In [37]:
# show merged dataframe using left join
df_left_join_example

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0125494,Shounen Keniya,1984,Animation,Japan,105,6.8
1,tt0031557,Law of the Pampas,1939,"Adventure, Western",USA,136,7.0
2,tt0997057,An Englishman in New York,2009,Drama,UK,1316,7.3
3,tt0097098,Come fare l'amore con un negro senza stancarsi,1989,Comedy,"Canada, France",294,4.6
4,tt0097007,La morte avrà i suoi occhi,1987,"Mystery, Sci-Fi, Thriller",USA,490,6.5
...,...,...,...,...,...,...,...
42923,tt2778674,Badri,2001,"Action, Sport",India,900,7.1
42924,tt0069947,Il giorno dello sciacallo,1973,"Crime, Drama, Thriller","UK, France",36547,7.9
42925,tt6319010,Santa Maria della Salute,2016,"Biography, Drama",Serbia,350,7.4
42926,tt10443846,Yeh Saali Aashiqui,2019,Thriller,India,2427,8.2
42927,tt1071785,Il dolce e l'amaro,2007,Drama,Italy,406,6.6

In [38]:
# shape
print(df_movies_sample.shape)
print(df_ratings.shape)
print(df_left_join_example.shape)

(42928, 5)
(85855, 3)
(42928, 7)

## **Exclusive Left Join : A - (A ∩ B)**

In [39]:
# left join
df1_merge_left_df2 = df1.merge(df2, how='left', on='id')
df1_merge_left_df2

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

In [40]:
# indicator=True
df1_merge_left_df2 = df1.merge(df2, how='left', on='id', indicator=True)
df1_merge_left_df2

  id  age           job     _merge
0  A   30           NaN  left_only
1  B   23           NaN  left_only
2  C   25        Doctor       both
3  D   22  Statistician       both

In [41]:
# query (for exclusive left join)
df1_merge_exclusive_left_df2 = df1_merge_left_df2.query('_merge == "left_only"')
df1_merge_exclusive_left_df2

  id  age  job     _merge
0  A   30  NaN  left_only
1  B   23  NaN  left_only

In [42]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_exclusive_left_df2.shape)

(4, 2)
(4, 2)
(2, 4)

In [43]:
# left join
df_left_join = df_movies.merge(df_ratings, how='left', on='imdb_title_id')
df_left_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [44]:
# indicator=True
df_left_join = df_movies.merge(df_ratings, how='left', on='imdb_title_id', indicator=True)
df_left_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [45]:
# query (for exclusive left join)
df_exclusive_left_join = df_left_join.query('_merge == "left_only"')
df_exclusive_left_join

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [46]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_exclusive_left_join.shape)

(85855, 5)
(85855, 3)
(0, 8)

More example for better understanding (of Exclusive Left Join)

In [47]:
# make a copy of df_movies dataframe
df_movies_2 = df_movies.copy()

In [48]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
df_movies_2.loc[:999, 'imdb_title_id'] = 'tt1234567890'

In [49]:
# merge df_movies_2 and df_raitngs (exclusive left join)
df_exclusive_left = df_movies_2.merge(df_ratings, how='left', on='imdb_title_id', indicator=True).query('_merge == "left_only"')
df_exclusive_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt1234567890,Miss Jerry,1894,Romance,USA,NaN,NaN,left_only
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,NaN,NaN,left_only
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark",NaN,NaN,left_only
3,tt1234567890,Cleopatra,1912,"Drama, History",USA,NaN,NaN,left_only
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
995,tt1234567890,Agente segreto Z1,1930,Drama,USA,NaN,NaN,left_only
996,tt1234567890,Tom Sawyer,1930,"Adventure, Comedy, Drama",USA,NaN,NaN,left_only
997,tt1234567890,Tonka Sibenice,1930,Drama,"Czechoslovakia, Germany",NaN,NaN,left_only
998,tt1234567890,Top Speed,1930,"Comedy, Musical, Romance",USA,NaN,NaN,left_only
999,tt1234567890,True to the Navy,1930,"Action, Comedy, Romance",USA,NaN,NaN,left_only

In [50]:
# shape
print(df_movies_2.shape)
print(df_ratings.shape)
print(df_exclusive_left.shape)

(85855, 5)
(85855, 3)
(1000, 8)

## **Right Join : B + (A ∩ B)**

In [51]:
# merge df1 and df2 on 'id' using right join
df1_merge_right_df2 = df1.merge(df2, how='right', on='id')

In [52]:
# merged dataframe using right join
df1_merge_right_df2

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

In [53]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_right_df2.shape)

(4, 2)
(4, 2)
(4, 3)

In [54]:
# merge df_movies and df_ratings (right join)
df_right_join = df_movies.merge(df_ratings, how='right', on='imdb_title_id')

In [55]:
# show merged dataframe using right join
df_right_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [56]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_right_join.shape)

(85855, 5)
(85855, 3)
(85855, 7)

More example for better understanding (of Right Join)

In [57]:
# extract 30% sample of the df_ratings dataframe
df_ratings_sample = df_ratings.sample(frac=0.3)

In [58]:
# merge df_movies and df_ratings_sample (right join)
df_right_join_example = df_movies.merge(df_ratings_sample, how='right', on='imdb_title_id')

In [59]:
# show merged dataframe using right join
df_right_join_example

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0058456,Jerry 8 e 3/4,1964,Comedy,USA,1985,6.4
1,tt0255797,Angels Crest,2002,Thriller,USA,110,5.9
2,tt3813334,Hank Boyd Is Dead,2015,"Comedy, Horror, Thriller",USA,103,5.7
3,tt0803080,Säg att du älskar mig,2006,Drama,Sweden,980,4.9
4,tt0342844,Nuda v Brne,2003,"Comedy, Drama, Romance",Czech Republic,797,7.2
...,...,...,...,...,...,...,...
25751,tt0163862,T-Rex: Back to the Cretaceous,1998,"Adventure, Family, Fantasy",USA,697,4.8
25752,tt3645178,Element,2016,Thriller,USA,155,3.8
25753,tt0439194,Head Trauma,2006,"Horror, Mystery, Thriller",USA,460,6.1
25754,tt0038172,Il figlio del fulmine,1945,"Action, Drama, Family",USA,293,6.6
25755,tt7510346,The Turning - La casa del male,2020,"Drama, Horror, Mystery","UK, Ireland, Canada, USA, India",7549,4.0

In [60]:
# shape
print(df_movies.shape)
print(df_ratings_sample.shape)
print(df_right_join_example.shape)

(85855, 5)
(25756, 3)
(25756, 7)

## **Exclusive Right Join : B - (A ∩ B)**

In [61]:
# right join
df1_merge_right_df2 = df1.merge(df2, how='right', on='id')
df1_merge_right_df2

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

In [62]:
# indicator=True
df1_merge_right_df2 = df1.merge(df2, how='right', on='id', indicator=True)
df1_merge_right_df2

  id   age           job      _merge
0  C  25.0        Doctor        both
1  D  22.0  Statistician        both
2  E   NaN    Accountant  right_only
3  F   NaN     Developer  right_only

In [63]:
# query (for exclusive right join)
df1_merge_exclusive_right_df2 = df1_merge_right_df2.query('_merge == "right_only"')
df1_merge_exclusive_right_df2

  id  age         job      _merge
2  E  NaN  Accountant  right_only
3  F  NaN   Developer  right_only

In [64]:
# shape
print(df1.shape)
print(df2.shape)
print(df1_merge_exclusive_right_df2.shape)

(4, 2)
(4, 2)
(2, 4)

In [65]:
# right join
df_right_join = df_movies.merge(df_ratings, how='right', on='imdb_title_id')
df_right_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [66]:
# indicator=True
df_right_join = df_movies.merge(df_ratings, how='right', on='imdb_title_id', indicator=True)
df_right_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [67]:
# query (for exclusive right join)
df_exclusive_right_join = df_right_join.query('_merge == "right_only"')
df_exclusive_right_join

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [68]:
# shape
print(df_movies.shape)
print(df_ratings.shape)
print(df_exclusive_right_join.shape)

(85855, 5)
(85855, 3)
(0, 8)

More example for better understanding (of Exclusive Left Join)

In [69]:
# make a copy of df_ratings dataframe
df_ratings_2 = df_ratings.copy()

In [70]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
df_ratings_2.loc[:999, 'imdb_title_id'] = 'tt1234567890'

In [71]:
# merge df_movies and df_raitngs_2 (exclusive right join)
df_exclusive_right = df_movies.merge(df_ratings_2, how='right', on='imdb_title_id', indicator=True).query('_merge == "right_only"')
df_exclusive_right

    imdb_title_id title year genre country  total_votes  mean_vote      _merge
0    tt1234567890   NaN  NaN   NaN     NaN          154        5.9  right_only
1    tt1234567890   NaN  NaN   NaN     NaN          589        6.3  right_only
2    tt1234567890   NaN  NaN   NaN     NaN          188        6.0  right_only
3    tt1234567890   NaN  NaN   NaN     NaN          446        5.3  right_only
4    tt1234567890   NaN  NaN   NaN     NaN         2237        6.9  right_only
..            ...   ...  ...   ...     ...          ...        ...         ...
995  tt1234567890   NaN  NaN   NaN     NaN          128        5.8  right_only
996  tt1234567890   NaN  NaN   NaN     NaN          160        6.6  right_only
997  tt1234567890   NaN  NaN   NaN     NaN          106        7.2  right_only
998  tt1234567890   NaN  NaN   NaN     NaN          172        6.2  right_only
999  tt1234567890   NaN  NaN   NaN     NaN          103        7.0  right_only

[1000 rows x 8 columns]

In [72]:
# shape
print(df_movies_2.shape)
print(df_ratings.shape)
print(df_exclusive_right.shape)

(85855, 5)
(85855, 3)
(1000, 8)